#![doc = "Generated by cli-helper v0.2.0"]
#![allow(unused, missing_docs)]
pub mod migrations {
    #[doc = "# SQL\n```sql\nCREATE TABLE IF NOT EXISTS identities (\r\n  id VARCHAR PRIMARY KEY NOT NULL,\r\n  username VARCHAR UNIQUE NOT NULL,\r\n  display_name VARCHAR NOT NULL,\r\n  created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (timezone('utc', NOW())),\r\n  expires TIMESTAMP WITH TIME ZONE DEFAULT (timezone('utc', NOW()) + '1 day'::INTERVAL)\r\n);\n```\n\n```sql\nCREATE UNIQUE INDEX IF NOT EXISTS identity_username_index ON identities (username);\n```"]
    pub fn migrate() -> [&'static str; 2usize] {
        [
            "CREATE TABLE IF NOT EXISTS identities (\r\n  id VARCHAR PRIMARY KEY NOT NULL,\r\n  username VARCHAR UNIQUE NOT NULL,\r\n  display_name VARCHAR NOT NULL,\r\n  created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT (timezone('utc', NOW())),\r\n  expires TIMESTAMP WITH TIME ZONE DEFAULT (timezone('utc', NOW()) + '1 day'::INTERVAL)\r\n);",
            "CREATE UNIQUE INDEX IF NOT EXISTS identity_username_index ON identities (username);",
        ]
    }
}
pub mod identities {
    #[doc = "# SQL\n```sql\nSELECT\r\n  id,\r\n  username,\r\n  display_name,\r\n  created,\r\n  expires\r\nFROM\r\n  identities\r\nWHERE\r\n  username = $1;\n```"]
    pub fn get_by_username() -> [&'static str; 1usize] {
        [
            "SELECT\r\n  id,\r\n  username,\r\n  display_name,\r\n  created,\r\n  expires\r\nFROM\r\n  identities\r\nWHERE\r\n  username = $1;",
        ]
    }
    #[doc = "# SQL\n```sql\nSELECT\r\n  id,\r\n  username,\r\n  display_name,\r\n  created,\r\n  expires\r\nFROM\r\n  identities\r\nWHERE\r\n  id = $1;\n```"]
    pub fn get_by_id() -> [&'static str; 1usize] {
        [
            "SELECT\r\n  id,\r\n  username,\r\n  display_name,\r\n  created,\r\n  expires\r\nFROM\r\n  identities\r\nWHERE\r\n  id = $1;",
        ]
    }
    #[doc = "# SQL\n```sql\nINSERT INTO\r\n  identities (id, username, display_name)\r\nVALUES\r\n  ($1, $2, $3)\r\nRETURNING\r\n  id,\r\n  username,\r\n  display_name,\r\n  created,\r\n  expires;\n```"]
    pub fn create() -> [&'static str; 1usize] {
        [
            "INSERT INTO\r\n  identities (id, username, display_name)\r\nVALUES\r\n  ($1, $2, $3)\r\nRETURNING\r\n  id,\r\n  username,\r\n  display_name,\r\n  created,\r\n  expires;",
        ]
    }
    #[doc = "# SQL\n```sql\nDELETE FROM\r\n  identities\r\nWHERE\r\n  id = $1;\n```"]
    pub fn delete_by_id() -> [&'static str; 1usize] {
        ["DELETE FROM\r\n  identities\r\nWHERE\r\n  id = $1;"]
    }
}
pub mod clean {
    #[doc = "# SQL\n```sql\nDELETE FROM\r\n  identities\r\nWHERE\r\n  expires > timezone('utc', NOW());\n```"]
    pub fn clean_expired() -> [&'static str; 1usize] {
        ["DELETE FROM\r\n  identities\r\nWHERE\r\n  expires > timezone('utc', NOW());"]
    }
}
